2022-04-09T17:17:57.595097+0300 ERROR What?!
Traceback (most recent call last):

  File "log_instr.py", line 53, in <module>
    nested(0)
    └ <function nested at 0x7f431a2f30d0>

> File "log_instr.py", line 49, in nested
    func(5, c)
    │       └ 0
    └ <function func at 0x7f431a5ca1f0>

  File "log_instr.py", line 44, in func
    return a / b
           │   └ 0
           └ 5

ZeroDivisionError: division by zero
2022-04-09T17:26:10.581773+0300 ERROR An error has been caught in function '<module>',
process 'MainProcess' (21170), thread 'MainThread' (140254978627392):
Traceback (most recent call last):

> File "log_instr.py", line 62, in <module>
    main()
    └ <function main at 0x7f8fa7a073a0>

  File "log_instr.py", line 60, in main
    divide(5, 0)
    └ <function divide at 0x7f8fa7cde1f0>

  File "log_instr.py", line 55, in divide
    return a / b
           │   └ 0
           └ 5

ZeroDivisionError: division by zero
